using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using PlayFab;
using PlayFab.ClientModels;

public class Runes : MonoBehaviour
{

    //Rune Type is "TRUE" for skills, "FALSE" for modifiers
    //Rune Skill Slot Numbers: Left Click = 5, Right Click = 6, 1 = 1, 2 = 2, 3 = 3, 4 = 4

    //Runes 1-6 reserved for base skills
    //Rune #1

    private int rune1_SkillSlot = 5; //Slot number of the skill
    private string rune1_Name = "SLAM"; //Skill name and is also the name of the method
    private string rune1_ID = "WarriorRune_1"; //Rune ID - could be changed to a number
    private string rune1_Info = ""; //Skill information that will be shown when skill mouse over a skill
    private bool rune1_Type = true; //Rune Type is "TRUE" for skills, "FALSE" for modifiers
    private int rune1_ResourceGeneration = 6; //How much resource generated by the skill
    private int rune1_ResourceUsage = 0; //How much resource used to be able to use the skill
    private int rune1_AttackRange = 3; //The attack range of the skill
    private float rune1_AttackSpeed = 0.5f; //The attack speed of the skill
    private float rune1_AttackRadius = 0f; //The attack radius for area damages
    private int rune1_Value = 0; //x value for example x% increased damage or x sec freeze

    //Rune #2
    private int rune2_SkillSlot = 6;
    private string rune2_Name = "CARVE";
    private string rune2_ID = "WarriorRune_2";
    private string rune2_Info = "";
    private bool rune2_Type = true;
    private int rune2_ResourceGeneration = 0;
    private int rune2_ResourceUsage = 20;
    private int rune2_AttackRange = 0;
    private float rune2_AttackSpeed = 0.5f;
    private float rune2_AttackRadius = 5f;
    private int rune2_Value = 0;

    //Rune #7 - Increase damage for primary skill
    private int rune7_SkillSlot = 5;
    private string rune7_Name = "PRIMARY_INC_DMG";
    private string rune7_ID = "WarriorRune_7";
    private string rune7_Info = "";
    private bool rune7_Type = false;
    private int rune7_ResourceGeneration = 0;
    private int rune7_ResourceUsage = 0;
    private int rune7_AttackRange = 0;
    private float rune7_AttackSpeed = 0f;
    private float rune7_AttackRadius = 0f;
    private int rune7_Value = 5;

    //Rune #8 - Increase critical hit chance for primary skill
    private int rune8_SkillSlot = 5;
    private string rune8_Name = "PRIMARY_INC_CRIT_HIT";
    private string rune8_ID = "WarriorRune_8";
    private string rune8_Info = "";
    private bool rune8_Type = false;
    private int rune8_ResourceGeneration = 0;
    private int rune8_ResourceUsage = 0;
    private int rune8_AttackRange = 0;
    private float rune8_AttackSpeed = 0f;
    private float rune8_AttackRadius = 0f;
    private int rune8_Value = 3;

    //Rune #9 - Increase fury generated by primary skill
    private int rune9_SkillSlot = 5;
    private string rune9_Name = "PRIMARY_INC_FURY";
    private string rune9_ID = "WarriorRune_9";
    private string rune9_Info = "";
    private bool rune9_Type = false;
    private int rune9_ResourceGeneration = 0;
    private int rune9_ResourceUsage = 0;
    private int rune9_AttackRange = 0;
    private float rune9_AttackSpeed = 0f;
    private float rune9_AttackRadius = 0f;
    private int rune9_Value = 9;

    //Rune #10 - Freeze hit enemies
    private int rune10_SkillSlot = 5;
    private string rune10_Name = "PRIMARY_FREEZE";
    private string rune10_ID = "WarriorRune_7";
    private string rune10_Info = "";
    private bool rune10_Type = false;
    private int rune10_ResourceGeneration = 0;
    private int rune10_ResourceUsage = 0;
    private int rune10_AttackRange = 0;
    private float rune10_AttackSpeed = 0f;
    private float rune10_AttackRadius = 0f;
    private int rune10_Value = 1;


    public static List<Rune> runes;

    private static float attackTimer = 0f;
    private GameObject targetEnemy;
    private static Animator playerAnimation;


    void Start()
    {
        playerAnimation = GetComponent<Animator>();
        runes = new List<Rune>();
        runes.Add(new Rune(rune1_SkillSlot, rune1_Name, rune1_ID, rune1_Info, rune1_Type, rune1_ResourceGeneration, rune1_ResourceUsage, rune1_AttackRange, rune1_AttackSpeed, rune1_Value));
        runes.Add(new Rune(rune2_SkillSlot, rune2_Name, rune2_ID, rune2_Info, rune2_Type, rune2_ResourceGeneration, rune2_ResourceUsage, rune2_AttackRange, rune2_AttackSpeed, rune2_Value));
        runes.Add(new Rune(rune7_SkillSlot, rune7_Name, rune7_ID, rune7_Info, rune7_Type, rune7_ResourceGeneration, rune7_ResourceUsage, rune7_AttackRange, rune7_AttackSpeed, rune7_Value));
        runes.Add(new Rune(rune8_SkillSlot, rune8_Name, rune8_ID, rune8_Info, rune8_Type, rune8_ResourceGeneration, rune8_ResourceUsage, rune8_AttackRange, rune8_AttackSpeed, rune8_Value));
        runes.Add(new Rune(rune9_SkillSlot, rune9_Name, rune9_ID, rune9_Info, rune9_Type, rune9_ResourceGeneration, rune9_ResourceUsage, rune9_AttackRange, rune9_AttackSpeed, rune9_Value));
        runes.Add(new Rune(rune10_SkillSlot, rune10_Name, rune10_ID, rune10_Info, rune10_Type, rune10_ResourceGeneration, rune10_ResourceUsage, rune10_AttackRange, rune10_AttackSpeed, rune10_Value));
    }

    void Update()
    {
        attackTimer += Time.deltaTime;
    }

    public void SLAM()
    {
        if(PlayerCombatManager.targetEnemy != null)
        {
            if (Vector3.Distance(transform.position, PlayerCombatManager.targetEnemy.transform.position) <= rune1_AttackRange)
            {
                if (attackTimer >= rune1_AttackSpeed)
                {
                    PlayerCombatManager.targetEnemy.GetComponent<Health>().TakeDamage(gameObject, 15);
                    attackTimer = 0f;
                    playerAnimation.SetTrigger("ATTACK 1");
                    if (PlayerCombatManager.playerCombatManager.GetPlayerResource() + rune1_ResourceGeneration <= 100)
                    {
                        PlayerCombatManager.playerCombatManager.SetPlayerResource(rune1_ResourceGeneration);
                    }
                    else
                    {
                        PlayerCombatManager.playerCombatManager.SetPlayerResource(100);
                    }
                    
                }
            }
        }          
    }

    public void CARVE()
    {
        if(PlayerCombatManager.playerCombatManager.GetPlayerResource() >= rune2_ResourceUsage)
        {
            Collider[] hitEnemies = Physics.OverlapSphere(gameObject.transform.position, rune2_AttackRadius);
            for (int i = 0; i < hitEnemies.Length; i++)
            {
                if (hitEnemies[i].CompareTag("Enemy"))
                {
                    hitEnemies[i].GetComponent<Health>().TakeDamage(gameObject, 100);         
                }
            }
            playerAnimation.SetTrigger("ATTACK 2");

            PlayerCombatManager.playerCombatManager.SetPlayerResource(-rune2_ResourceUsage);
        }
   
    }

    bool InAttackRange(int attackRange)
    {

        if (Vector3.Distance(transform.position, PlayerCombatManager.targetEnemy.transform.position) <= attackRange)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
}


